version: '3.9 '

services:
  smartshop:
    build:
      context: .
    container_name: smartshop
    volumes:
      - .:/smartshop/
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres_db
    ports:
      - 8000:8000
    environment:
      - DB_HOST=postgres_db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=2356

  redis:
    image: redis:latest
    container_name: redis

  postgres_db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: postgres_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2356


